Cleanup wrapper scripts
We're now using a function to run the application, and local variables
so that any wrapper-related stuff doesn't pollute the environment of the
application itself.

We're also using exec now because that's more accurate to how these
wrapper script should work.

diff --git a/bin/emacs b/bin/emacs
--- a/bin/emacs
+++ b/bin/emacs
@@ -3,22 +3,15 @@
 function run_server() {
   local SERVER_NAME=emacs
   local SERVER="$(which -a "$SERVER_NAME" | sed "0,\|^$0\$|d" | head -n 1)"
+  [[ ! -e "$SERVER" ]] && echo "$SERVER_NAME could not be found" && exit 1
 
-  if [[ -e "$SERVER" ]]; then
-    $SERVER ${@}
-  else
-    echo "$SERVER_NAME could not be found"
-  fi
+  exec $SERVER ${@}
 }
 
 function run_client() {
   local CLIENT_NAME=emacsclient
   local CLIENT="$(which -a "$CLIENT_NAME" | head -n 1)"
-
-  if [[ ! -e "$CLIENT" ]]; then
-    echo "$CLIENT_NAME could not be found"
-    exit 1
-  fi
+  [[ ! -e "$CLIENT" ]] && echo "$CLIENT_NAME could not be found" && exit 1
 
   # If we're running in terminal mode actually wait
   local WAIT_ARG="-n"
@@ -26,15 +19,12 @@ function run_client() {
     [[ $ARG == "-t" || $ARG == "--tty" || $ARG == "-nw" ]] && WAIT_ARG=""
   done
 
-  $CLIENT -a="" -c $WAIT_ARG ${@}
+  exec $CLIENT -a="" -c $WAIT_ARG ${@}
 }
 
 # If we're trying to start server, do so
 for ARG in "${@}"; do
-  if [[ "$ARG" == *"daemon" ]]; then
-    run_server ${@}
-    exit $?
-  fi
+  [[ "$ARG" == *"daemon" ]] && run_server ${@}
 done
 
 run_client ${@}
diff --git a/bin/spotify b/bin/spotify
--- a/bin/spotify
+++ b/bin/spotify
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 
-APP="$(which -a "$(basename "$0")" | sed "0,\|^$0\$|d" | head -n 1)"
-if [[ -e "$APP" ]]; then
-  $APP --force-device-scale-factor=2 ${@}
-else
-  echo "$(basename "$0") could not be found"
-fi
+function run() {
+    local APP_NAME="$(basename "$0")"
+    local APP="$(which -a "$APP_NAME" | sed "0,\|^$0\$|d" | head -n 1)"
+    [[ ! -e "$APP" ]] && echo "$APP_NAME could not be found" && exit 1
+
+    exec $APP --force-device-scale-factor=2 ${@}
+}
+
+run
diff --git a/bin/vmware b/bin/vmware
--- a/bin/vmware
+++ b/bin/vmware
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
 
-APP="$(which -a "$(basename "$0")" | sed "0,\|^$0\$|d" | head -n 1)"
-if [[ -e "$APP" ]]; then
-  GDK_SCALE=1
-  GDK_DPI_SCALE=0.5
-  $APP ${@}
-else
-  echo "$(basename "$0") could not be found"
-fi
+function run() {
+    local APP_NAME="$(basename "$0")"
+    local APP="$(which -a "$APP_NAME" | sed "0,\|^$0\$|d" | head -n 1)"
+    [[ ! -e "$APP" ]] && echo "$APP_NAME could not be found" && exit 1
+
+    GDK_SCALE=1
+    GDK_DPI_SCALE=0.5
+    exec $APP ${@}
+}
+
+run
